name = "domain_puns"
version = "1.0.0"

description = "CLI tool to help you pick out a domain with a fun top-level (if it exists)"
licences = ["Apache-2.0"]
repository = { type = "github", user = "spenserblack", repo = "domain-puns" }

[dependencies]
argv = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
